<div style="background:linear-gradient(to right, #4facfe, #00f2fe);
padding:15px;
border-radius:10px;
color:white;">

<h1>📊 Netflix Data Analysis Portfolio Project</h1>

<h3>🟢 Excel  
🔵 SQL  
🟣 Power BI  
🟠 Python  
🐼 Pandas  
🔢 NumPy  
📊 Matplotlib</h3>

</div>

## 🎯 Import Data From `CSV` to `Pandas`

In [1]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\ayush\OneDrive\Desktop\ExcelData\Netflix Proj\Netflix Userbase.csv"
)

df.head()

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration
0,1,Basic,10,15-01-22,10-06-23,United States,28,Male,Smartphone,1 Month
1,2,Premium,15,05-09-21,22-06-23,Canada,35,Female,Tablet,1 Month
2,3,Standard,12,28-02-23,27-06-23,United Kingdom,42,Male,Smart TV,1 Month
3,4,Standard,12,10-07-22,26-06-23,Australia,51,Female,Laptop,1 Month
4,5,Basic,10,01-05-23,28-06-23,Germany,33,Male,Smartphone,1 Month

## 🎯 Check `Data Type`

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User ID            2500 non-null   int64
 1   Subscription Type  2500 non-null   object
 2   Monthly Revenue    2500 non-null   int64
 3   Join Date          2500 non-null   object
 4   Last Payment Date  2500 non-null   object
 5   Country            2500 non-null   object
 6   Age                2500 non-null   int64
 7   Gender             2500 non-null   object
 8   Device             2500 non-null   object
 9   Plan Duration      2500 non-null   object
dtypes: int64(3), object(7)
memory usage: 195.4+ KB

## 🎯 Convert Date DataType `Obj` to `datetime64[ns]`

In [3]:
df["Join Date"] = pd.to_datetime(df["Join Date"], format = "mixed")

df.head()

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration
0,1,Basic,10,2022-01-15,10-06-23,United States,28,Male,Smartphone,1 Month
1,2,Premium,15,2021-05-09,22-06-23,Canada,35,Female,Tablet,1 Month
2,3,Standard,12,2023-02-28,27-06-23,United Kingdom,42,Male,Smart TV,1 Month
3,4,Standard,12,2022-10-07,26-06-23,Australia,51,Female,Laptop,1 Month
4,5,Basic,10,2023-01-05,28-06-23,Germany,33,Male,Smartphone,1 Month

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User ID            2500 non-null   int64
 1   Subscription Type  2500 non-null   object
 2   Monthly Revenue    2500 non-null   int64
 3   Join Date          2500 non-null   datetime64[ns]
 4   Last Payment Date  2500 non-null   object
 5   Country            2500 non-null   object
 6   Age                2500 non-null   int64
 7   Gender             2500 non-null   object
 8   Device             2500 non-null   object
 9   Plan Duration      2500 non-null   object
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 195.4+ KB

In [5]:
df["Last Payment Date"] = pd.to_datetime(df["Last Payment Date"], format = "mixed")
df.head()

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration
0,1,Basic,10,2022-01-15,2023-10-06,United States,28,Male,Smartphone,1 Month
1,2,Premium,15,2021-05-09,2023-06-22,Canada,35,Female,Tablet,1 Month
2,3,Standard,12,2023-02-28,2023-06-27,United Kingdom,42,Male,Smart TV,1 Month
3,4,Standard,12,2022-10-07,2023-06-26,Australia,51,Female,Laptop,1 Month
4,5,Basic,10,2023-01-05,2023-06-28,Germany,33,Male,Smartphone,1 Month

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User ID            2500 non-null   int64
 1   Subscription Type  2500 non-null   object
 2   Monthly Revenue    2500 non-null   int64
 3   Join Date          2500 non-null   datetime64[ns]
 4   Last Payment Date  2500 non-null   datetime64[ns]
 5   Country            2500 non-null   object
 6   Age                2500 non-null   int64
 7   Gender             2500 non-null   object
 8   Device             2500 non-null   object
 9   Plan Duration      2500 non-null   object
dtypes: datetime64[ns](2), int64(3), object(5)
memory usage: 195.4+ KB

## 🎯 Check `NULL` values in the DataSet

In [7]:
df.isnull().sum().sum()

np.int64(0)

## 🎯 Check `Duplicate` rows in the DataSet

In [8]:
df.duplicated().sum()

np.int64(0)

## 🎯 Check `Duplicate` columns in the DataSet

In [9]:
df.columns.duplicated().sum()

np.int64(0)

## 🎯 Check `Row Size` in the DataSet

In [10]:
df.size

25000

## 🎯 Check `Column Size` in the DataSet

In [11]:
df.columns.size

10

## 🎯 Check `Column Name` in the DataSet

In [12]:
df.columns

Index(['User ID', 'Subscription Type', 'Monthly Revenue', 'Join Date',
       'Last Payment Date', 'Country', 'Age', 'Gender', 'Device',
       'Plan Duration'],
      dtype='object')

## 🎯 Check columns contain `numeric data`

In [13]:
df.select_dtypes(include='number').columns

Index(['User ID', 'Monthly Revenue', 'Age'], dtype='object')

## 🎯 Check columns contain `Text data`

In [14]:
df.select_dtypes(include= 'object').columns

Index(['Subscription Type', 'Country', 'Gender', 'Device', 'Plan Duration'], dtype='object')

## 🎯 Pick `Random Rows`

In [15]:
df.sample(5)

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration
892,893,Standard,13,2022-07-30,2023-01-07,United States,42,Female,Smart TV,1 Month
1808,1809,Standard,15,2022-09-17,2023-06-07,Canada,40,Female,Tablet,1 Month
696,697,Basic,12,2022-06-10,2023-06-29,Spain,43,Male,Smart TV,1 Month
418,419,Standard,11,2022-10-30,2023-06-27,Spain,27,Female,Laptop,1 Month
192,193,Standard,11,2022-05-08,2023-06-25,United Kingdom,50,Male,Laptop,1 Month

## 🎯 Check DataSet `shape`

In [16]:
df.shape

(2500, 10)